### ISSUE TITLE
16655 - Yemenite Jews - lat-lon for song 9229 incorrect

### ISSUE THREAD

**Issue by dorshilton** [theglobaljukebox/cantometrics#105]
9229: Performers are Yemenite Jews but the album is called Folk music of Palestine and was recorded there.
https://folkways.si.edu/folk-music-of-palestine/islamica-world/album/smithsonian

**Comment by stellasilbert** [comment]
Noted [Recorded in Palestine] in the metadata, but we use the homeland of performers not the recording location.
