### ISSUE TITLE
18294 - Kazakh - society lat-lon incorrect 

### ISSUE THREAD

**Issue by dorshilton** [theglobaljukebox/cantometrics#110]
Should be moved to somewhere on the Kazakh steppe, perhaps the lat-lon of song 9389

**Comment by stellasilbert** [comment]
Noticed that lat-lons for songs 3120 and 9204 are incorrect as well. They should be in the Ural region of Kazakhstan, not Russia. Changing to 51.22, 51.37. Then, society lat-lon can be the average song lat-lon (46.98, 67.73).
