### ISSUE TITLE
17557 - South Jakarta - rename, reassign some songs, correct song and society lat-lons

### ISSUE THREAD

**Issue by stellasilbert** [theglobaljukebox/cantometrics#115]
Society 17557, currently named South Jakarta, includes songs from many different regions of Java. I suggest the following:

- Rename society 17557 "Javanese", and keep songs 3354, 3352, 3353, 2765, 1, 877, 3981 assigned to it. Make society lat-lon average of song lat lons (-7.21, 109.89). Match to xd751, language java1254. My reasoning for broadening the name of the society rather than splitting into different regions of Java is in order to facilitate match with xd751/Ib2 (Javanese).
- Rename society 12365 "Sundanese" and reassign songs 1824, 3356, 3355, 3358, 1823, 1562, 3357 to it. No D-PLACE match. Language sund1252. Change song location name to West Java, W C Indonesia for all songs (currently the lat-lon is the same for all songs except 3357 but the name varies). Change song lat-long for 3357 to  -7.09, 107.66 to match the others with same location. Make society lat-lon -7.09, 107.66 as well.

Question for @kirbykat and @annalwood - what to do about songs 3979 and 3980?
[3979](https://www.loc.gov/resource/afc2004004.ms431706/?st=slideshow#slide-8) is from Banten, likely performed by [Bantenese people](https://en.wikipedia.org/wiki/Bantenese_people) (subgroup of Sundanese).
[3980](https://www.loc.gov/resource/afc2004004.ms431706/?st=slideshow#slide-10) lists location as "Baduy, West Java," however [Baduy](https://en.wikipedia.org/wiki/Baduy_people) seems not to be a location but is actually a subgroup of Bantenese people, who are themselves a subgroup of Sundanese people. Both songs are from the same source and I cannot find tape notes for it, so this is all the info I have.
Options are: 
1) Assign both songs to society 12365. Reasoning: Bantenese and Baduy are both of Sundanese ethnicity.
2) Create new "Bantenese" society and assign both songs to it. Reasoning: To differentiate Bantenese  from West Java Sundanese.
3) Create two new societies: Bantenese (assign song 3979, language bant1285) and Baduy (assign song 3980, language badu1237). Reasoning: To differentiate Baduy as a distinctive group with their own dialect.

**Comment by stellasilbert** [comment]
See also theglobaljukebox/parlametrics#9

**Comment by stellasilbert** [comment]
For now, I have implemented the bulleted solutions, and went with option 1 regarding songs 3979 and 3980-- assigned them to society 12365 (Sundanese). Always possible to split them off later if needed.

**Comment by annalwood** [comment]
Stella, Would you be able to list the Javanese songs with the society names
you propose plus our current metadata and links to audio?  We can then ask
Philip Yampolsky to better identify them.


One problem is that there is no record of Ted Schwartz recordings in Java.
This attribution was transferred from Alan's and Jaap kunst's Columbia
World Lib album, Indonesia. I think these may have been recorded by Kunst.
I am sorry you had to spend so much time on this


Those recordings in Jakarta should be listed as maybe urban Jakarta.
Otherwise your solutions (first bullet) make sense, given the languages.
There should be note on Baduy and Banten cultures in the metadata.

**Comment by stellasilbert** [comment]
Here is a list of the songs, copied from the metadata sheet. Let me know if you need this in a separate doc or email. You can also just use the existing metadata spreadsheet and look up these society numbers.

I added the note you suggested for the Banten and Baduy songs, and listed the two songs from Jakarta as Urban Jakarta. 

<google-sheets-html-origin><style type="text/css"></style>

song_id | Local_latitude | Local_longitude | Homeland_latitude | Homeland_longitude | Region | Division | Subregion | Area | Preferred_name | Society_location | society_id | Audio_notes | Duration | Audio_file | archivalsource_id | Song | Genre | Song_notes | Performers | Instruments | Vocalist_gender | Lyrics | Living_metadata | Recorded_by | Year | Publisher | Publcation_collection | Repository | Classification_notes | Metadata_notes | Sources | Source_tag | fileexists? |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3351 | -7.09 | 107.66 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Sundanese | West Java, W C Indonesia | 12365 |   |   | PENDING | 3A59.A3 | Pantum | Epic |   | Male solo, zither, two clappers | Male Voice; Zither; Clappers | Men |   |   | Bernard Ijzerdraat | 1960 | Chant du Monde | Chants Et Danses D'Indonésie. Le Chant du Monde LDY-4179. |   |   |   |   | @CDM1960ChantsEtDansesD'Indonesie | No |   |   |   |   |   |   |   |   |   |   |   |  
1562 | -7.09 | 107.66 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Sundanese | West Java, W C Indonesia | 12365 |   | 0:03:58 | T5424R01 | T1342.5 | Sundanese Song 1 |   | Atmospheric saron and kulintang tone clouds, an easy paced recital with bowed rebab, flurries of sound | Female solo, male solo, rebab, bowed lute, saron, metalophone, kulintang, gong row, drums, gongs | Female Voice; Male Voice; Rebab, Bowed Lute; Saron, Metalophone; Kulintang, Gong Row; Drums; Gongs | Mixed adults |   |   | Radio Republik Indonesia | 1963 | Radio Republik Indonesia | Robert Garfias collection, Sunda. Tape VIII.5. | Radio Republik Indonesia, Jakarta, Indonesia; Dept. Of Ethnomusicology, University of California, Irvine; Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   | Double coded; see coding sheet 1825 | Dubs made by Mantle Hood from RRI (Radio Republik Indonesia) while he was in Indonesia | @GC1963RRIDubs | Yes |   |   |   |   |   |   |   |   |   |   |   |  
1823 | -7.09 | 107.66 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Sundanese | West Java, W C Indonesia | 12365 | Speed fluctuations on original, which make this piece unusable; use WS24.01, T5424R01, instead | 0:01:55 | T5424R02 | T1342.6 | Sundanese Song 3 |   | Atmospheric saron and kulintang tone clouds, a slightly hurried recital with bowed rebab, flurries of sound | Female and male voices, rebab, bowed lute, saron, metalophone, kulintang, gong row, drums, gongs | Female Voices; Male Voices; Rebab, Bowed Lute; Saron, Metalophone; Kulintang, Gong Row; Drums; Gongs | Mixed adults |   |   | Radio Republik Indonesia | 1963 | Radio Republik Indonesia | Robert Garfias collection | Radio Republik Indonesia, Jakarta, Indonesia; Dept. Of Ethnomusicology, University of California, Irvine; Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   | Dubs made by Mantle Hood from RRI (Radio Republik Indonesia) while he was in Indonesia | @GC1963RRIDubs | Yes |   |   |   |   |   |   |   |   |   |   |   |  
1824 | -7.09 | 107.66 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Sundanese | West Java, W C Indonesia | 12365 |   | 0:03:00 | T5424R59 | T1498.2 | Javanese Song 2 | Gamelan |   | Female solo, gamelan, flute, zither | Female Voice; Gamelan; Flute; Zither | Women |   |   |   |   | Previously Unpublished | Bali II and Java I. Folkways Archives. Tape 1. 2. | Ralph Rinzler Folklife Archives and Collections, Smithsonian Center for Folklife and Cultural Heritage. http://www.folklife.si.edu/archive; Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   |   | @RRFACNDBaliIIJavaI | Yes |   |   |   |   |   |   |   |   |   |   |   |  
3980 | -7.09 | 107.66 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Sundanese | Baduy, West Java, W C Indonesia | 12365 |   | 0:00:59 | T5424R65 | T3083.4b | Javanese Song 4 |   | Antiphonal song with zither | Male leader, mixed chorus, zither | Male Voice; Mixed Voices; Zither | Mixed adults |   |   | Bernard Ijzerdraat (B. Suryabrata) | 1955-60 | Indravox | Bernard Ijzerdraat Recordiings in Java | Copy in Alan Lomax Collection, American Folklife Center, Library of Congress | Likely performed by Baduy people, a Bantenese people, who are a subgroup of Sundanese. Classified as Sundanese. -SS |   |   | @Indravox1955-60JavaneseSong4 | Yes |   |   |   |   |   |   |   |   |   |   |   |  
3358 | -7.09 | 107.66 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Sundanese | West Java, W C Indonesia | 12365 |   | 0:03:16 | T5424R68 | T1356.2D7 | Senggot Adu Manis | Gamelan | Ketjapi Orchestra | Rukun Wargi, gamelan, Nji Iti Narem, rebab | Gamelan; Rebab |   |   |   | Jaap Kunst | 1952 | Previously Unpublished | Japp Kunst Collections, Ethnomusicology Archives, University of Amsterdam | Ethnomusicology Archives, University of Amsterdam; Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   | Copies provided by Ethnomusicology Archive, Univeristy of Amsterdam, Linnaeusstraat 2a, Amsterdam, Archive # C/49. Copyright | @JKC1952SenggotAduManis | Yes |   |   |   |   |   |   |   |   |   |   |   |  
3355 | -7.09 | 107.66 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Sundanese | West Java, W C Indonesia | 12365 |   | 0:03:18 | T5424R70 | T1356.2D3 | Javanese Song 1 | Gamelan |   | Male solo, gamelan, gambus | Male Voice; Gamelan; Gambus | Men |   |   | Jaap Kunst | 1952 | Previously Unpublished | Japp Kunst Collections, Ethnomusicology Archives, University of Amsterdam | Ethnomusicology Archives, University of Amsterdam; Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   | Copies provided by Ethnomusicology Archive, Univeristy of Amsterdam, Linnaeusstraat 2a, Amsterdam, Archive # E/25. Copyright | @JKC1952JavaneseSong1 | Yes |   |   |   |   |   |   |   |   |   |   |   |  
3356 | -7.09 | 107.66 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Sundanese | West Java, W C Indonesia | 12365 |   | 0:01:21 | T5425R01m | T1356.2D1 | Sundanese Song 4 | Gamelan |   | Female solo, gamelan | Female Voice; Gamelan | Women |   |   | Jaap Kunst | 1952 | Previously Unpublished | Japp Kunst Collections, Ethnomusicology Archives, University of Amsterdam | Ethnomusicology Archives, University of Amsterdam; Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   | Copies provided by Ethnomusicology Archive, Univeristy of Amsterdam, Linnaeusstraat 2a, Amsterdam, Archive # E/25. Copyright | @JKC1952SundaneseSong4 | Yes |   |   |   |   |   |   |   |   |   |   |   |  
3979 | -6.4 | 106.06 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Sundanese | Banten, Java, W C Indonesia | 12365 |   | 0:02:18 | T5424R64 | T3083.3 | Wawayangan | Gamelan |   | Male solo, gamelan | Male Voice; Gamelan | Men |   |   | Bernard Ijzerdraat (B. Suryabrata) | 1955-60 | Indravox | Bernard Ijzerdraat Recordiings in Java | Copy in Alan Lomax Collection, American Folklife Center, Library of Congress | Likely performed by Bantenese people, a subgroup of Sundanese. Classified as Sundanese. -SS |   |   | @Indravox1955-60Wawayangan | Yes |   |   |   |   |   |   |   |   |   |   |   |  
3357 | -7.09 | 107.66 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Sundanese | West Java, W C Indonesia | 12365 |   | 0:01:14 | T5424R67 | T1356.1B2 | Lutung Kasarung | Epic Song; Pantun | Pantun, sung epic, part of a recitation of a Sundanese pantun | Male solo | Male Voice | Men |   |   | Bernard Ijzerdraat | 1955-60 | Radio Republik Indonesia | Bernard Ijzerdraat Recordings, Ethnomusicology Archives, University of Amsterdam, AZ-25. | Ethnomusicology Archives, University of Amsterdam; Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   | Copies provided by Ethnomusicology Archive, Univeristy of Amsterdam, Linnaeusstraat 2a, Amsterdam. Copyright | @RRI1955-60IjzerdraatRecordings | Yes |   |   |   |   |   |   |   |   |   |   |   |  
3354 | -7.64 | 112.6 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Javanese | Trawas, Mojokerto, East Java, Indonesia | 17557 |   | 0:01:19 | T5424R69 | T1356.2D10,2 | Nini Towong | Children's Song; Game Song; Spirit Song | Children's game song, a doll, house, and garden spirit |   |   |   |   |   | Jaap Kunst | 1952 | Previously Unpublished | Japp Kunst Collections, Ethnomusicology Archives, University of Amsterdam | Ethnomusicology Archives, University of Amsterdam; Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   | Copies provided by Ethnomusicology Archive, Univeristy of Amsterdam, Linnaeusstraat 2a, Amsterdam, Archive # E/25. Copyright | @JKC1952NiniTowong | Yes |   |   |   |   |   |   |   |   |   |   |   |  
2765 | -7.61 | 110.71 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Javanese | Java, W C Indonesia | 17557 |   |   | NULL |   | Javanese Song |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | No |   |   |   |   |   |   |   |   |   |   |   |  
3353 | -7.61 | 110.71 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Javanese | Java, W C Indonesia | 17557 |   | 0:03:17 | T5423R49 | T1513.1 | Javanese Song 3 | Gamelan | Atmospheric gamelan | Female solo, mixed chorus, gamelan | Female Voice; Mixed Voices; Gamelan | Mixed adults |   |   | Ted Schwartz | 1963 | Previously Unpublished | Ted Schwartz collection | Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   |   | @TSC1963JavaneseSong3 | Yes |   |   |   |   |   |   |   |   |   |   |   |  
3352 | -7.61 | 110.71 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Javanese | Java, W C Indonesia | 17557 |   | 0:03:07 | T5424R61m | T1498.7 | Javanese Poetry Chant | Chant |   | Female solo | Female Voice | Women |   |   |   |   | Previously Unpublished | Bali II and Java I. Folkways Archives. Tape 1. 7. | Ralph Rinzler Folklife Archives and Collections, Smithsonian Center for Folklife and Cultural Heritage. http://www.folklife.si.edu/archive; Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   |   | @RRFACNDBaliIIJavaI | Yes |   |   |   |   |   |   |   |   |   |   |   |  
1 | -7.57 | 110.82 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Javanese | Surakarta, Central Java, W C Indonesia | 17557 |   | 0:03:28 | T5424R43 | 3A33.30; WFS8.6; WFS8ALT.6 | Kembang Mas | Gamelan | Golden Flower, classical Javanese gamelan, pelog composition | Solo female Mardularas (Applying Herself to Harmony), Gamelan Kangjeng Kjahi Mangunsih (The Most Venerable Sir Practising Love) | Female Voice; Gamelan Kangjeng Kjahi Mangunsih | Women |   |   | Jaap Kunst | 1952 | Columbia Records | Columbia World Library of Folk and Primitive Music: Volume VII: Indonesia. Columbia Masterworks KL215 | Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   | Jaap Kunst, author of notes | @CFPM1955Indonesia | Yes |   |   |   |   |   |   |   |   |   |   |   |  
877 | -6.2 | 106.84 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Urban Jakarta | Jakarta, Java, W C Indonesia | 62584 | 1 sec dropout at start | 0:03:50 | T5414R02 | T1237.4 | Kroncong Persembahaniku | Popular Song | Indonesian pop song | Female solo, Orkes Keroncong Puspa, orchestra | Female Voice; Orchestra | Women |   |   | Asia House; Ted Schwartz | 1963 | Previously Unpublished | Asia House Recordings. Tape #1481. T1237.4. | Asia House; Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   | Sent to Alan Lomax by the Asia House | @AHR1963KroncongPersembahaniku | Yes |   |   |   |   |   |   |   |   |   |   |   |  
3981 | -6.2 | 106.84 |   |   | Southeast Asia | Island S E Asia | Greater Sundas | Java | Urban Jakarta | Jakarta, Java, W C Indonesia | 62584 |   | 0:03:22 | T5424R66 | T3084.C3 | Surilang | Gamelan | Pseudo-Latin flavor, ie. Cha-Cha-Cha, and West African rhythmic accents in xylophone, only at one point | Female solo, rebab, gamelan | Female Voice; Rebab; Gamelan | Women |   |   | Bernard Ijzerdraat (B. Suryabrata) | 1955-60 | Indravox | Bernard Ijzerdraat Recordiings in Java | Copy in Alan Lomax Collection, American Folklife Center, Library of Congress |   |   |   | @Indravox1955-60Surilang | Yes |   |   |   |   |   |   |   |   |   |   |   |

**Comment by annalwood** [comment]
It would be better on separate spreadsheet formatted so easy to read


www.culturalequity.org

https://archive.culturalequity.org

www.theglobaljukebox.org


*“The precise role of the artist is to illuminate that darkness, blaze
roads through that vast forest, so that we will not, in all our doing, lose
sight of its purpose, which is to make the world a more human dwelling
place."  --- James Baldwin*
