### ISSUE TITLE
song 3170 incorrectly coded

### ISSUE THREAD

**Issue by dorshilton** [theglobaljukebox/cantometrics#118]
line 1 should be code 4 (one solo singer after another - it's a duet between male and female singers, says so in the metadata), but currently coded 8 (leader-group alteration)

**Comment by SamPassmore** [comment]
Hi Dor, 
Could you point to the file you are looking at for this?
I.e. is it in the raw/ data folder or cldf/ data folder?

**Comment by stellasilbert** [comment]
Corrected on canto_codings google sheet
