### ISSUE TITLE
song 9088 should be double coded

### ISSUE THREAD

**Issue by dorshilton** [theglobaljukebox/cantometrics#122]
Kaluli song - two female singers alternate. Should be coded 10 and 4 (to indicate just two singers), now coded simply 10 (in cldf and raw).

The same performance type is true for 9089, 9096, 9097, 9098, 30097, 30098.

**Comment by stellasilbert** [comment]
Corrected to double code of 10 and 4 for songs 9088, 9089, 9096, 9097, 9098, 30097, and 30098 (on canto_codings google sheet).
