### ISSUE TITLE
13140 - Nova Scotia - Either split or rename

### ISSUE THREAD

**Issue by stellasilbert** [theglobaljukebox/cantometrics#127]
Although this society is called Nova Scotia, some of the songs assigned to it are by Anglo-Canadians from other parts of Canada. I would suggest either of two options:

1. Rename society "Anglo-Canadians" or something like that, and tweak geographic classification to be broader than Nova Scotia. Society lat-lon is already in Ontario. I think this society used to be called British Canadians or something similar but was renamed Nova Scotia without reassigning any songs.

2. Split into two societies:
13140 - Nova Scotia - Keep songs 585, 586, 587, 606, 607 assigned to it. Make society lat-lon average of song lat-lons.
New society - Ottawa Valley Anglo-Canadians (or similar) - Assign songs 608 and 609. Make society lat-lon average of song lat-lons.

I defer to @annalwood on which of these options is preferable. 

Also, songs 608 and 609 should have homeland lat-lon (51.65, -0.08), since the singer was born in Enfield, England.

**Comment by annalwood** [comment]
Agreed. Ottawa Valley coincides with any other source?  Check please
