### ISSUE TITLE
What line is Tremolo

### ISSUE THREAD

**Issue by SamPassmore** [theglobaljukebox/cantometrics#288]
I was going through the variable descriptions in 
etc/codes.csv & etc/variables.csv

line 30 has descriptions for tremolo but in the variables file Tremolo is line 31. 

Do we know which is correct?

**Comment by SamPassmore** [comment]
No it hadnt been fixed - but I have done it now. 

When changing files using the web browser, make sure you commit the change with a message saying what was changed at the bottom.

**Comment by stellasilbert** [comment]
Ok, thank you! I must have just done the first step but not committed it.

**Comment by SamPassmore** [comment]
No probs! You can think of commiting as saving effectively.
