### ISSUE TITLE
Kate - SUGGEST CORRECTING THE WAY NORTHERN AUSTRALIAN SONGS HAVE BEEN ASSIGNED TO YOLNGU LANGUAGE

### ISSUE THREAD

**Issue by stellasilbert** [theglobaljukebox/cantometrics#62]
Kate's notes with Stella's comments:

<google-sheets-html-origin><style type="text/css"></style>

Done |   |   |   | 30080 | Yolngu |   | Reassign  SONG ID 9396 to Society ID 11078 (Wadjiginy). JUSTIFICATION: (From liner notes at this URL (http://www.earthtube.com/research/disco/disc07.html)): "The song "A: Rdanganjej Rangandaj" [is] in the WONGGA style of northwestern Arnhem Land. Songman Lawrence speaks songs and lyrics in the *Wogadj language* of Delissaville." Note also that Alice Moyle states in notes accompanying "Songs From the Northern Territory 1: Music From Western Arnhem Land": "In Gunwinggu, a dance song is borg or gunborg, in the Daly River languages, it is wongga, also spelt wangga." And "smaller groups traditionally located south of the Daly River [...] were referred to collectively in the 1960s, as Wagatj" [Note that Wogadj is wadj1254]. (In other words, song ID 9396 should not be matched to 30080 (Yolngu))
-- | -- | -- | -- | -- | -- | -- | --
  | Looking into song ID 3351, I think it was mistakenly assigned to an album of dijeridu music, but it is actually a West Javanese fine arts song (track A3, Pantum) from this album: https://www.discogs.com/Various-Chants-Et-Danses-DIndon%C3%A9sie/release/2611147 See coding sheet https://www.loc.gov/resource/afc2004004.ms431509/?st=slideshow#slide-2 So I have corrected the metadata accordingly. I can't find digital audio to purchase online, but if we have the LP in our collection we can digitize it. --Stella |   |   | 30080 | Yolngu |   | Reassign SONG ID 3351 to "Burarra" (society ID 62533). JUSTIFICATION: (1) Has same lat lon as another song recorded by Hiatts (9370) and which is assigned to the Burarra. (2) In the notes that accompany that song (found online), the Hiatt(s) state: "[the] Burara [...] own manigai, and Mulumbug is the only one among them who sings a song of the borg type." This suggests to me that the Hiatts may have recorded this manigai among the Burarra? Or have I missed some information that suggests this song should be assigned to Yolngu (entirely possible, and also maybe the most parsimonious thing to do when there is no clear information is to go with what GJB assigned originally, with the assumptio that it was assigned for a reason? I think it just depends on how much the past process is trusted - was it done by an expert, or quickly by someone trying to organize the data?).
  |   |   |   |   |   |   |  
  | I remember reviewing the Australia materials about a year ago and adding these statements based on liner notes, but now I can't find anything about the Ritharrngu people in the original liner notes either. So, I think you're right that this must have been a mistake on my part, due to a misunderstanding of the moiety system. Thank you for catching that, and I have removed those mentions of the Ritharrngu people. --Stella |   |   | 30080 | Yolngu |   | SONG IDS 9275,1220,1221,1222,9312:  QUESTION: A number of the song descritpions include this statement: "song from the Yirtija [Dua] Moiety (a branch of the Ritharrngu people, who are themselves part of the Yolngu people)". BUT, when I look up the original liner notes and/or related papers, I find no mention of the Ritharrngu.  I did find one mention in online liner notes of the Yolngu dialect group rirr1238 (Rirratjingu) -- easy to confuse with Ritharrngu (rita1239).
  | I'm looking back into the songs classified as 30080 Yolngu, and noting a few things:1) Songs 1220 and 1229 seem to be from the same ceremony as song 1225, and I believe they were both recorded at Oenpelli (Gunbalanya) and should both be matched to Kunwinjku, as 1225 is, based on this source: https://press-files.anu.edu.au/downloads/press/p116081/html/ch20.xhtml?referer=&page=26#toc-anchor. However, I also want to point out that this ceremony is restricted and secret. I understand that the audio will not be streaming on the GJB, but just want to check in about the song descriptions in the metadata. Should we simply say these are songs from the sacred restricted Ubar ceremony and not go any further with the descriptions?2) Songs 1221 and 1222 are described as:  "north-central or North-East Arnhem Land clan songs (Manikay) (side 14, cut 3; sides 15, 16) recorded from a Delissaville resident [named Alandi] who, according to Elkin’s notes, had been transferred there on parole from south-west Arnhem Land." (https://press-files.anu.edu.au/downloads/press/p116081/html/ch18.xhtml?referer=&page=24). So, I'm not sure how helpful the location of Northeast Arnhem Land is in tracking down the specific Yolngu dialect this might be sung in. It might be safest to just leave as Yolngu.3) Again, with song 9275, the lat-long is based on the rather general description in the liner notes of "Central Arnhem Land," so not sure how accurate a match to the Djinba dialect/subgroup would be.In general, I think it might be safest to leave the culture name as Yolngu if we don't have explicit information indicating a specific subgroup, since the locations given are often pretty broad. But I will leave this up to Anna.--Stella |   |   | 30080 | Yolngu |   | WHY THIS MATTERS: we could assign the Ritharnngu language to SONG IDS 9275,1220,1221,1222,9312 (which either include the note about Ritharrngu, or are from the same lat/lon and recording date as a song that includes such a note). OR, we could match each of these songs geographically to the Yolngu languages they are closest to. This would, for example, lead SONG IDS 1220, 1221, 12222 to be matched to dhuw1249 (and thus also to D-PLACE societies B88, and Id2) and SONG ID 9275 to djin1252 (and thus to D-PLACE society B85). SONG 9312 and 1227 would probably best be matched to guma1253 "Gumatj".
  |   |   |   | 30080 | Yolngu |   | The reason I think the metadata note on "a branch of the Ritharrngu people may be a mistake: it is easy to misunderstand how moieties and language groups work. Here is what I understand:  (1) historically, many Yolngu-speaking peoples were referred to as "Murngin" (note that Yolngu is a language family with a number of member languages and dialects). (2) All Yolngu groups, and some neighbouring non-Yolngu groups, recognize two "Moieties" that transcend individual tribes/language groups: the Dua Moiety at the Yiritja Moiety. This means that two individuals could both belong to the Yiritja Moiety, but speak different languages. I wonder if a previous database editor assumed after reading once that a Yiritja/Dua moiety member belonged to the Ritharnngu people that ANYONE who belonged to one of these moieties was a Ritharnngu speaker? (and just pasted the same phrase into each row that also mentioned these moieties?)
  | I suggest matching this song, and 1220, with Kunwinjku, see note above. --Stella |   |   | 30080 | Yolngu |   | SONG ID 1229: geographically, best match would be to mang1382 or gunw1252 (in the latter case, the song should probably be reassigned to society "Kunwinjku"). Is there any addiitonal evidence for why this should be assumed to be a Yolngu group?

**Comment by stellasilbert** [comment]
Reassigned songs 1220 and 1229 to Kunwinjku.

Kept all remaining songs assigned to 30080, and kept language match as dhuw1249, even though guma1253 might be a better fit for songs 9312 and 1227. Reasoning: Even though location info for those two songs is specific enough to match them to guma1253 language, the location info is not very specific for the rest of the songs, so I suggest keeping all together under one "Yolngu" society, matched with the D-PLACE society "Yolngu, Dhuwal" (which uses language dhuw1249) and noting that it may not be a perfect match, rather than trying to break down the society by language.

**Comment by annalwood** [comment]
yes, isn't that the way it was? Yoingu?  It was quite a puzzle.


www.culturalequity.org

https://archive.culturalequity.org

www.theglobaljukebox.org


*“The precise role of the artist is to illuminate that darkness, blaze
roads through that vast forest, so that we will not, in all our doing, lose
sight of its purpose, which is to make the world a more human dwelling
place."  --- James Baldwin*

**Comment by stellasilbert** [comment]
Yep, that's the way it was. Just noting that I didn't take Kate's suggestion of splitting it up.
