### ISSUE TITLE
Kate - PROBLEMS WITH SONG-to-CULTURE LINKS IN SONG METADATA 

### ISSUE THREAD

**Issue by stellasilbert** [theglobaljukebox/cantometrics#63]
Kate's notes:

I started looking at liner notes on the Smithsonian webpage when trying to understand why Shipibo-Conibo were considered different cultures. I did this by just clicking on the links in the "Sources" column of the SongMetadata sheet. I was surprised to find that the song with ID 897 that was assigned to "Shipibo-Conibo" in my dataset was assigned to "Cocama" on the Smithsonian page. I checked a few more surrounding songs, and found a handful of mismatches in the culture assigned to a song in my spreadsheet vs. the culture assigned to the song on the Smithsonian page. This is obviously a big concern, because it introduces a new level of error: coded data for a given song could be assigned to the wrong culture, making it seem like that culture has different types of songs than it does. I suggest someone go through and double check the culture for all songs for which we have a hyperlink - I only got through about 45. (Or, maybe the Smithsonian site is wrong?!?)

I suggest checking all those songs I haven't yet checked that have electronic liner notes -- it shouldn't take too long and would eliminate easy-to-correct mistakes re: attribution of cantometrics data to correct culture ID

<google-sheets-html-origin><style type="text/css"></style>

CURRENT soc_id | song_id | CURRENT CULTURE | Sources | SHOULD BE ( ACCORDING TO SMITHSONIAN PAGE LINKED IN "SOURCES") | SHOULD HAVE CULTURE ID
-- | -- | -- | -- | -- | --
13135 | 896 | Asháninka | Notes by Harry Tschopik, Jr.,American Museum of Natural History; Willard Rhodes, Columbia University; http://www.folkways.si.edu/TrackDetails.aspx?itemid=11291 | Shipibo-Conibo | 14026
14026 | 897 | Shipibo-Conibo | Notes by Harry Tschopik, Jr.,American Museum of Natural History; Willard Rhodes, Columbia University; http://www.folkways.si.edu/TrackDetails.aspx?itemid=11272 | Cocama | 13927
24091 | 2499 | S Peruvian Quechua | This record is a two LP set.; http://www.folkways.si.edu/TrackDetails.aspx?itemid=28665 | Q'ero | 62301
24102 | 3378 | Ch'unchu | http://www.folkways.si.edu/TrackDetails.aspx?itemid=14464 | Mestizo | ??62454
13927 | 9445 | Cocama | Notes by Harry Tschopik, Jr.,American Museum of Natural History; Willard Rhodes, Columbia University; http://www.folkways.si.edu/TrackDetails.aspx?itemid=11288 | Asháninka | 13135

**Comment by stellasilbert** [comment]
Additional note on sources: The hyperlinks to songs on the Folkways website that are in the "Sources" column of the metadata sheet don't seem to work anymore. But, all Cantometrics songs are linked to their sources through the source tags in the "Source Tag" column, which have hyperlinks in the GJB Data Sources spreadsheet . I didn't create the Sources column so I can't speak to its accuracy, but I created the Source Tags. In most cases they link to the whole album, not a specific song, but I feel pretty confident about their accuracy. (The specific song can be located via the archival source number, which gives the track number on the album). See my notes below about each of the specific examples, but it looks like in several cases someone put the link to the wrong song in the "Sources" column because multiple songs on the album from different cultures have the same name (ex. "Social Dance"). Some cases were genuine errors, which I have corrected. I would suggest deleting the hyperlinks in the Sources column because they don't work anymore and some of them are incorrect. Could also be nice to hyperlink the Source Tags to their URLs (when there is a URL). --Stella

**Comment by stellasilbert** [comment]
Stella's notes:

<google-sheets-html-origin><style type="text/css"></style>

  |   | CURRENT soc_id | song_id
-- | -- | -- | --
Confirmed our society info is correct, no changes need to be made. Wrong song with same name was linked; I have removed hyperlink. --Stella | Issue36 | 13135 | 896
Confirmed our society info is correct, no changes need to be made. Wrong song with same name was linked; I have removed hyperlink. --Stella | Issue37 | 14026 | 897
Corrected to Q'ero (62301) and corrected song lat lon based on liner notes. --Stella | Issue38 | 24091 | 2499
Liner notes confirm this is indeed performed by Peruvian mestizos from Arequipa. I suggest either of two options: 1) renaming the society currently called "Lima" (62454) to "Peruvian Mestizo," (one of the 3 recordings currently associated with that society is already by Peruvian mestizos from Apurimac, not Lima), and assigning song 3378 to that society, or 2) if it is important to keep Lima mestizos separate, create a new Peruvian Mestizo society and assign 3378 and NC91c (the song from Apurimac) to it. --Stella | Issue39 | 24102 | 3378
Confirmed our society info is correct, no changes need to be made. Wrong song with same name was linked; I have removed hyperlink. --Stella | Issue40 | 13927 | 9445

**Comment by stellasilbert** [comment]
Additional note on sources: The hyperlinks to songs on the Folkways website that are in the "Sources" column of the metadata sheet don't seem to work anymore. But, all Cantometrics songs are linked to their sources through the source tags in the "Source Tag" column, which have hyperlinks in the GJB Data Sources spreadsheet . I didn't create the Sources column so I can't speak to its accuracy, but I created the Source Tags. In most cases they link to the whole album, not a specific song, but I feel pretty confident about their accuracy. (The specific song can be located via the archival source number, which gives the track number on the album). See my notes below about each of the specific examples, but it looks like in several cases someone put the link to the wrong song in the "Sources" column because multiple songs on the album from different cultures have the same name (ex. "Social Dance"). Some cases were genuine errors, which I have corrected. I would suggest deleting the hyperlinks in the Sources column because they don't work anymore and some of them are incorrect. Could also be nice to hyperlink the Source Tags to their URLs (when there is a URL). --Stella

**Comment by stellasilbert** [comment]
Re: song 3378, I decided to create new Arequipa society and assign to that, because it seems to be a distinct subculture from Lima.

All other song-specific issues here have been corrected.

Broken links in Sources field have been removed across all song metadata.

**Comment by annalwood** [comment]
Yoingu as I recall was a designation for a blend of different groups, or
for them when they got together.  There should be a note on this in the
metadata, and there are sources


www.culturalequity.org

https://archive.culturalequity.org

www.theglobaljukebox.org


*“The precise role of the artist is to illuminate that darkness, blaze
roads through that vast forest, so that we will not, in all our doing, lose
sight of its purpose, which is to make the world a more human dwelling
place."  --- James Baldwin*

**Comment by stellasilbert** [comment]
Think maybe you meant to put your most recent comment on this thread:  theglobaljukebox/cantometrics#62. If possible, try to keep your comments on the relevant thread, so that they are easier to find and understand later should someone need to look back. But your suggestion sounds good! It looks like the note about Yolngu being an amalgamated group is already in the culture description in the metadata.
