### ISSUE TITLE
Kate - Rename societies currently called "XXXX Immigrant" to "XXXX American"?

### ISSUE THREAD

**Issue by stellasilbert** [theglobaljukebox/cantometrics#72]
Kate's notes:

<google-sheets-html-origin><style type="text/css"></style>

Rename societies currently called "XXXX Immigrant" to "XXXX American"? (To be consistent with e.g., Scandinavian Americans, German Americans, etc.)? |  
-- | --
62542 | Greek Immigrant
62523 | S Italian Immigrant/ Campania
62545 | Chinese Immigrant
62524 | Sardinian Immigrants

**Comment by SamPassmore** [comment]
Just to confirm Stella.

The change here are:
Greek Immigrant -> Greek American
S Italian Immigrant / Campania -> South Italian American / Campania
Chinese Immigrant -> Chinese American
Sardinian Immigrant -> Sardinian American

**Comment by stellasilbert** [comment]
Yes. There was also one more: S Italian American/ Calabria. I've already implemented these changes in the society metadata and in the metadata for the relevant datasets. I suppose I should paste this issue into the Parlametrics repository too, because some of these are Parlametrics societies.

**Comment by stellasilbert** [comment]
theglobaljukebox/parlametrics#8
