### ISSUE TITLE
Maasai: 20956 Line 1

### ISSUE THREAD

**Issue by SamPassmore** [theglobaljukebox/cantometrics#94]
The coding notes suggest that Line 1 should never be coded as a 3
https://github.com/theglobaljukebox/cantometrics/blob/main/etc/codes.csv#L4

But Masai have this line coded as a 3. 

Should this be checked?

**Comment by stellasilbert** [comment]
Only song 3875 has this problem, correct?

Looking at the [original coding sheet](https://www.loc.gov/resource/afc2004004.ms431701/?st=slideshow#slide-50), the symbol for point 4 was circled but the number 3 was circled. So, I'm guessing a double code of 4 and 12 was meant for line 1. This sounds right, listening to the audio.

I've corrected line 1 to a double code of 4 and 12.
