### ISSUE TITLE
Merge Turkey (27765) & “Black Sea” (30065)

### ISSUE THREAD

**Issue by SamPassmore** [theglobaljukebox/cantometrics#99]
There are two Turkish speaking societies in GJB. 

Turkey (27765) & “Black Sea” (30065)

All songs seem to relate to Turkish folk music, so it is unclear why the societies have been split. 

All Turkey songs are recorded by Harald Schultz, as part of a previously unpublished collection. 
Black sea songs are recorded by numerous people - but are recorded from albums such as: Turkey: A Musical Journey; Musik Aus Der Turkei; Songs and Dances of Turkey; Folk and Traditional Music of Turkey - with no specific reference to groups at the Black Sea. 

Suggestion: Merge Turkey & Black Sea

**Comment by stellasilbert** [comment]
Reassigned songs from 30065 to 27765 and removed 30065 from society metadata.
